### PR TITLE
Implemented email verification and user information refresh functionalities

### PR DESCRIPTION
**Pull request by itswisdomagain**
Added IsEmailVerified property to User class

Call any of these methods to begin email verification flow:
`
    FirebaseAuthProvider.SendEmailVerificationAsync(string firebaseToken)
    FirebaseAuthProvider.SendEmailVerificationAsync(FirebaseAuth auth)
`

You can also send email address verification email when creating a user account
`
    FirebaseAuthProvider.CreateUserWithEmailAndPasswordAsync(string email, string password, bool sendVerificationEmail);
or
    FirebaseAuthProvider.CreateUserWithEmailAndPasswordAsync(string email, string password, string displayName, bool sendVerificationEmail);
`

Finally, call any of these methods at anytime to update the user's information and determine if the email verification process is complete via the User.IsEmailVerified prope6rty
`
    firebaseAuthLink.RefreshUserDetails() //where firebaseAuthLink => result of your authentication process (sign up/log in)
    FirebaseAuthProvider.GetUserAsync(string firebaseToken)
    FirebaseAuthProvider.GetUserAsync(FirebaseAuth auth);
` 

For Issue: #6

### CODE REVIEW

**Comment by hardcodet** [comment]
This doesn't allow me to send a verification email if I don't have the token anymore (e.g. if the mail never arrived). Is this a limitation of the Firebase API or this implementation (I noticed that I can reset my password with just the email, so I assume this should be possible as well).

Thanks,
Philipp

**Comment by itswisdomagain** [comment]
Hi Philipp,

"This doesn't allow me to send a verification email if I don't have the token anymore"
Yeah, it's a Firebase limitation.

But you can always get the token and re-send the email if the user logs in again. See below:

If the email never arrived but the user was successfully registered, then whenever the user next logs in, you can check the verification status:
`
  User.IsEmailVerified
`
 and re-send the verification email using either of the following
`
  FirebaseAuthProvider.SendEmailVerificationAsync(string firebaseToken)
or
  FirebaseAuthProvider.SendEmailVerificationAsync(FirebaseAuth auth)
`

As long as the user remains authenticated, either after the initial sign up or after a subsequent login, you have access to the token and can thus re-send the verification email.

**Comment by hardcodet** [comment]
Yeah, that's my current workaround - I keep the token after a login in case they want a resend, so I'll be fine. Still a very artificial limitation given that you can reset the pw with just the email address.

Thanks for the reply!

**Comment by hardcodet** [comment]
Btw, that IsEmailVerified flag has been always false for me - see the thread in the Issues section.

**Comment by itswisdomagain** [comment]
Oh.
Seen the issue. It's a funny one, will look into it soon.

**Comment by Kapusch** [comment]
Hello @itswisdomagain ,

I'm currently doing some tests with the first authentication flow, and I really appreciate your work on the email verification included in CreateUserWithEmailAndPasswordAsync method.

I've encountered the same issue described in #21 , with authLink.User.IsEmailVerified which is always false, except after having invoked RefreshUserDetails method.

I'm a bit afraid that I need to call RefreshUserDetails every time I want to do some stuff with user account.

Is it intended to use RefreshUserDetails even after a fresh authentication with SignInWithEmailAndPasswordAsync method ?

Thanks in advance !

**Comment by itswisdomagain** [comment]
Hey @Kapusch, turns out I never found the time to investigate the issue then. But thinking about it now, the behaviour seems reasonable to a great extent.

According to the [firebase auth api doc for signInWithEmailAndPassword](https://firebase.google.com/docs/reference/rest/auth#section-sign-in-email-password), the expected response contains no `isEmailVerified` property. Here's an example response:
```
{
  "localId": "ZY1rJK0eYLg...",
  "email": "[user@example.com]",
  "displayName": "",
  "idToken": "[ID_TOKEN]",
  "registered": true,
  "refreshToken": "[REFRESH_TOKEN]",
  "expiresIn": "3600"
}
```

[This workaround](https://github.com/step-up-labs/firebase-authentication-dotnet/issues/21#issuecomment-361622109) is at least a good work around.

> Is it intended to use RefreshUserDetails even after a fresh authentication with SignInWithEmailAndPasswordAsync method ?

That isn't ideal though, so it would be a better idea to modify the sign in methods to _also_ perform user details fetching after every successful signup.

This is already done for `SignInWithCustomTokenAsync`, for example:
https://github.com/step-up-labs/firebase-authentication-dotnet/blob/f75ec11cb7df2d907c0f22f1e6b01dbc034eb90e/src/Firebase.Auth/FirebaseAuthProvider.cs#L51-L57

Fix is offered in #112.

**Comment by Kapusch** [comment]
Thanks for your fast reactivity !

Your comment opened my eyes on the actual return of signInWithPassword method provided by Firebase.

I put a comment on #112 about using RefreshUserDetails

**Pull request merged**
