### PR TITLE
Removed duplicate curly brace

### PR DESCRIPTION
**Pull request by sheindel**
Duplicate curly brace leftover when https://github.com/step-up-labs/firebase-authentication-dotnet/pull/113 was merged

### CODE REVIEW

**Review by Kapusch — APPROVED** [review]
I confirm removing this duplicated brace fixes the parsing error I had while authenticating with email / password

**Review by davvit — COMMENTED** [review]
FYI:   on line 162, there is missing comma after tenantId value as well

 sb.Append($"\"tenantId\":\"{tenantId}\",");

**Review by asinino — CHANGES_REQUESTED** [review]
Because the previous strings from StringBuilder has $ decorator it should be used here also, with the $ in front of the string the double brackets makes sense (escape character).

`sb.Append($"\"returnSecureToken\":true}}");`

The line 162:
`sb.Append($"\"tenantId\":\"{tenantId}\"");`

Also needs a fix with a trailling comma at the end, it will make possible to have another property being added next to it (the token I've talked above). So it must be like this:
`sb.Append($"\"tenantId\":\"{tenantId}\",");`

@Author: Please, Please, after the above fix apply this PR because this bug makes this library useless, other signin methods may be working, but this is the primary signin method wich make the current state of the library useless.

**Comment by sheindel** [comment]
@davvit  I added the comma fix

@asinino yes I understand why the extra curly brace was there. For reference, @author is an actual GitHub account and didn't tag me, you need to use the person's handle, so @bezysoftware would probably be a good bet

**Comment by bezysoftware** [comment]
Can you please bump version in csproj? I'll merge and publish to nuget then

**Comment by sheindel** [comment]
@bezysoftware all set now

**Review by asinino — APPROVED** [review]
It's perfect now, thanks for your time.

**Comment by bezysoftware** [comment]
Published, it should appear shortly. Thx!

**Pull request merged**
