### PR TITLE
Enable Apple Sign In

### PR DESCRIPTION
**Pull request by Kapusch**
I have forked the current last release version (3.4.0) in order to enable Firebase authentication with an ID token obtained via Apple Sign In.
Apple Sign In can be set up with [Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?context=xamarin%2Fxamarin-forms&tabs=ios#apple-sign-in).

Note : I was not able to launch unit tests in "Visual Studio for Mac 2019"

### CODE REVIEW

**Comment by robertmaxted** [comment]
are these commits going to be merged at any point?

**Comment by bezysoftware** [comment]
Published to nuget under v3.7.0. I would however recommend using v4 (in alpha)

**Comment by robertmaxted** [comment]
@bezysoftware  Thanks for the update! When will the docs be available for  v4? (I'd they already exist could you point me to them please Thomas? Thanks again! 👍

**Comment by robertmaxted** [comment]
Found the docs! Ignore the above question 👍

**Pull request merged**
