### PR TITLE
Add handling of exception for GetUserAsync method

### PR DESCRIPTION
**Pull request by sergeylopatyuk**
Added generation FirebaseAuthException for invalid data in the method GetUserAsync

### CODE REVIEW

**Comment by sergeylopatyuk** [comment]
Hellooo

**Comment by bezysoftware** [comment]
Hi, thanks for the PR.!
1) can you resolve the conflicts that github is reporting?
2) can your replace explicit type definitions with var keyword?

**Comment by sergeylopatyuk** [comment]
Done

**Comment by bezysoftware** [comment]
Thanks!

**Pull request merged**
